sudo: required

services:
  - docker

script:
  - docker build -t aurorafw/travis-archlinux .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push aurorafw/travis-archlinux;
    fi
